---
- name: Dante setup
  hosts: dante
  tasks:
    - name: Install dante
      package:
        name: dante-server
        state: present
    - name: Ensure dante is enabled and running
      service:
        name: danted
        state: started
        enabled: true
