---
- name: Create a started container
  hosts: localhost
  connection: local
  tasks:
        lxc_container:
            name: test-container-started
            container_log: true
            template: ubuntu
            state: started
            template_options: --release trusty
