---
- name: Squid setup
  hosts: squid
  tasks:
    - name: Install squid
      package:
        name: squid
        state: present
    - name: Ensure squid service is enabled and running
      service:
        name: squid
        state: started
        enabled: true
